### PR TITLE
Add support for parsing WOFF2 fonts.

### LINKED ISSUE #1: Add support for woff2 fonts
Currently woff2 fonts return "unsupported font format". Please support woff2.

### PR DESCRIPTION
**Pull request by dmitshur**
~~DO NOT MERGE. This PR depends on [font/woff2#1](https://dmitri.shuralyov.com/font/woff2/...$changes/1) being merged first.~~ This PR is open for review and discussion.

This PR implements support for WOFF2 files and resolves #1 by using a dedicated `woff2` parser package.

~~The `woff2` package isn't live yet, it still needs review. First, I suggest reviewing its public API. Once that looks good, we can move on to reviewing its internal code. You can see and review its API on redpen:~~

~~https://redpen.io/rk9a75c358f45654a8~~

~~(If you don’t have have a redpen account and would rather not make one for posting review comments, feel free to post them here instead.)~~

**Edit:** See my [comment](https://github.com/ConradIrwin/font/pull/14#issuecomment-364811169) below for an update.

This PR is meant to continue the conversation from #1. /cc @ConradIrwin @bramp

### CODE REVIEW

**Comment by bramp** [comment]
I've added a few comments via redpen. I have to admit, I don't find that the easiest, because it makes things like searching hard, and I'm used to reviewing APIs in code. But I've given it a go :)

General comment, is this seems separate from ConradIrwin/font in a few places, doesn't depend on same types, such as Tag. This is ok but just wanted to explicitly call that out.

**Comment by dmitshur** [comment]
> I've added a few comments via redpen. I have to admit, I don't find that the easiest, because it makes things like searching hard, and I'm used to reviewing APIs in code. But I've given it a go :)

@bramp, thank you for the review and for playing along with my experiment! It has been very insightful and helpful to me.

In hindsight, I can see that showing you _only_ the godoc view to review is suboptimal in many ways. Not being able to search because it was an image (redpen is meant for design reviews; I was kinda abusing it) is an important one, thanks for pointing it out. But more than that, I've realized that there are many more relevant details in code that don't make it into the `godoc` view:

- First, you couldn't see the commit message, which described the scope and limitations of the commit.

- Second, you couldn't see the TODO comments and `return fmt.Errorf("not implemented")` statements in code, which help provide context on certain things.

So now I think that showing you the `godoc` view in addition to the entire normal diff would be better. You can read the code as usual, and _then_ see how it appears in `godoc` once you're more familiar with the details. I suspect that would be a better experience.

I've replied to your existing comments on redpen, but in the meantime, could you please take another look at the actual code change (with commit message and TODO comments visible):

https://dmitri.shuralyov.com/font/woff2/...$changes/1

_(Please be aware that my code review tool is still a work in progress and **the commenting functionality is not finished**. You can only view the change—but can't leave review comments on it yet. If you don't mind, just leave comments here instead. I realize the line numbers aren't being shown yet, so it might be hard... Thanks and sorry for the unusual setup; this is an [active project](https://github.com/shurcooL/home/pull/16) of mine.)_ 😄

**Comment by dmitshur** [comment]
Friendly ping. Let me know if there's anything I can do to help make progress on this.

If there are any concerns about the approach, just let me know.

**Comment by ConradIrwin** [comment]
@shurcooL Are you happy with the woff2 library yet? I'm happy for this to depend on that if you're not going to change the API anymore :)

**Comment by dmitshur** [comment]
@ConradIrwin It is ready from my side. I've responded to all review comments so far, and I was just waiting in case there would be any further review comments.

I'll go ahead and merge that change now. Then, I'll resolve the conflicts in this PR (it had some conflicts with #15) so it can be merged.

> if you're not going to change the API anymore

I'm not going to change the API in the short term, but it's best to think of it as v0 API. I do want to evolve it as I make further progress on the encoder and discover opportunities for API improvement. If there are any changes to its APIs, I will be sending PRs here to update the code and keep `ConradIrwin/font` building. See https://github.com/shurcooL/SLA#breaking-api-changes for more information about my approach.

**Comment by ConradIrwin** [comment]
Sounds good

I like the SLA idea :D I should figure out what I can commit to, but it might be embarrassingly low...

Sent via Superhuman ( https://sprh.mn/?vip=conradirwin@gmail.com )

**Comment by dmitshur** [comment]
I've merged https://dmitri.shuralyov.com/font/woff2/...$changes/1. Going to resolve conflicts here now.

**Comment by dmitshur** [comment]
I've rebased and resolved conflicts. PTAL.

**Comment by ConradIrwin** [comment]
looks good, thanks!

**Pull request merged**
